version: '3.7'

services:

  webapp
    build: ./testapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./testapp/:/usr/src/testapp/
    ports:
      - 8000:8000

volumes:
  static_volume: